[package]
name = "chetro-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"

macroquad = "0.4.14"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
